const {Schema,  model, Types} = require('mongoose')

const schema = new Schema({
    dateParsing:{type:Date, required:true, unique:true},
   cbr:[{
        AUD:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        AZN:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        GBP:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        AMD:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        BYN:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        BGN:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        BRL:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        HUF:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        HKD:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        DKK:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        USD:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        EUR:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        INR:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        KZT:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        CAD:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        KGS:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        CNY:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        MDL:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        NOK:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        PLN:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        RON:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        XDR:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        SGD:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        TJS:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        TRY:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        TMT:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        UZS:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        UAH:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        CZK:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        SEK:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        CHF:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        ZAR: {
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        KRW:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
        JPY:{
            data:{
                name:{type:String},
                nominal:{type:Number},
                value:{type:Number},
            }
        },
   }],
   isLast:{type:Boolean, required:true, unique:false,default:true}
})

module.exports = model('Valutes',schema)